* Заводная Кложа [Groovy Clojure]

или Groovy вместо deftype

https://github.com/darkleaf/clj-groovy

28 марта 2024
Михаил Кузьмин

Нанимаю в [[https://gmonit.ru][gmonit.ru]]

* API

Все работает подобно ~deftype~ или ~defrecord~.
Со всеми их особенностями.

#+begin_src clojure
  (g/defclass MyClass)

  (->MyClass arg)
#+end_src

Можно сразу инстанцировать объект,
например фукнцию или реализацию протокола.

#+begin_src clojure
  (g/defobject my-obj)

  (my-obj arg) ;; if IFn
  (protocol/method my-obj) ;; if Protocol
#+end_src

* История
** Шаблонизаторы

Эра [[https://htmx.org/][htmx]], [[https://hotwired.dev/][Hotwire]].

В Clojure сейчас все плохо с шаблонизацией текста и html.
Только-только начали появляться проекты, вроде [[https://github.com/onionpancakes/chassis][chassis]],
или ~#html~ в squint.

Почему бы вместо шаблонизатора не использовать полноценный язык? 😁

Но пока я не определился с решением.

** Шаблонизаторы (подробно)

- Нет зрелых шаблонизаторов
  - уязвимости
  - стандарты
  - удобство

- Java шаблонизаторы, selmer
 - заточены на java подобный синтаксис (dot notation),
   а мапы могут содержать, например ключи с неймспейсами.
   #+begin_src clojure
     {:user/name "Mikhail"
      :org/name  "GMonit"
      :ru.hsl.gmonit.apm.awesome-package/name "..."
      'foo/name  "..."
      "name"     "..."}
   #+end_src
   #+begin_src erb
     <%= model.:user/name %>
     <%= model.:ru.hsl.gmonit.apm.awesome-package/name %>
   #+end_src
 - компиляция, кэши
 - мешают разработке через REPL
 - изобретают заново неймспейсы
   когда есть функции и ~clojure.lang.Var~

- шаблонизация текста
 - multiline string literal

   Никак не сделают в Clojure

   #+begin_src clojure
     (defn greeting [name] """
       Привет, <(name)>!
       Хочешь "немного" кавычек?
     """)
   #+end_src

- [[https://github.com/weavejester/hiccup][hiccup]]
  заброшен
- [[https://github.com/yogthos/Selmer][selmer]]
  классический шаблонизатор, со всеми их проблемами
- [[https://github.com/onionpancakes/chassis][chassis]]
  перспективный, только html5

Решение пока не выбрано

** expression vs statement

Бывают *полезные* алгоритмы, которые уже написаны на C подобном языке,
и используют его на полную.

- foo[x++]
- foo[++x]
- ранние возвраты (одобряю)
- continue   в случайных местах
- переменные в случайных местах

Очень тяжело переписывать алгоритмы с statament based на expression based язык.

#+begin_src js
  function (node) {
    var fieldsUsed = 0
    for (var fieldIdx = 0; fieldIdx < fieldCount; fieldIdx++) {
    //                                            ________^^
      var fieldVal = node.fields[fieldsUsed++]
      //                         __________^^
      if (fieldVal === null) {
        // ...
        continue
      }

      var fieldName = fieldSpec.name
      var fieldType = fieldSpec.type
      // ...
      decodedNode[fieldName] = fieldVal
    }
  }
#+end_src

#+begin_src clojure
  (dotimes [fieldIdx fieldsCount]
    (let [...]
      (if (= fieldType "node")
        (decodeNodeField decodedNode fieldSpec)
        (let [fieldVal (nth nodeFields @fieldsUsed)
              _        (vswap! fieldsUsed inc)]
          (do
            (when ...
              (let ...
                (if ...))))
#+end_src

Немного помогает ~<<-~
#+begin_src clojure
  (<<-
   (let [...])
   (if guard return)
   (do side-effect)
   (if guard return)
   (for [...])
   (doseq [...]))
#+end_src

Но volatile это не уберет

** Java interop

- ~gen-class~
  требует компиляции,
  хотя его можно сделать динамическим

- ~proxy~
  медленный

- свои классы исключений

Red Planet Labs
- [[https://github.com/redplanetlabs/proxy-plus][proxy-plus]]
- [[https://github.com/redplanetlabs/defexception][defexception]]

* Groovy

- похож на Java

- никак не умрет

- выпускает новые релизы несколько раз в месяц
  5.0.0-alpha

- поддерживает новые Java фичи
  вроде рекордов и лямбд SAM

- заточен под встраивание

- удобное API компилятора

- компилируется в байт-код, не интерпретируется

- @CompileStatic
  убирает непрямой вызов методов

- [[https://issues.apache.org/jira/browse/GROOVY-7492][@POJO]]

  #+begin_quote
    This opens up some of Groovy's powerful transforms to the wider Java community.
    Groovy can effectively be used as a Lombok-style pre-processor for some Java classes.
  #+end_quote

- runtime metaprogramming
  - monkey patching
  - method missing
  - DSL

  Не востребовано в контексте дополнения Clojure.

- compile-time metaprogramming
  - @InheritConstructors
  - @Delegate
  - @DeletageTo
    билдеры без methodMissing
  - API для AST преобразований
    они изобрели макросы!

- операторы

  #+begin_src groovy
    myIFn.invoke(a, b, c)
    ;; vs
    myIFn(a, b, c)
  #+end_src

- добавление методов к любому классу

  #+begin_src groovy
    obj.with { inc.invoke(it) }
    ;; vs
    obj.with(inc)
  #+end_src

  работает с @CompileStatic

- @OperatorRename
  Groovy 5 alpha

  #+begin_src groovy
    @OperatorRename(plus='add')
    def testAddOfTwoFractions() {
      var half = Fraction.of(1, 2)
      var third = Fraction.of(1, 3)
      assert half.add(third) == Fraction.of(5, 6)  // old style still works
      assert half + third == Fraction.of(5, 6)     // fraction '+' operator!
      //      ____^
    }
  #+end_src

* ClassLoader

** GroovyClassLoader

- начинал с него
- компилирует скрипты
  и классы
- можно реализовать интерфейс
- *нельзя* ~(import MySuperClass)~
- *нельзя* import в другом скрипте
- только объекты
- или работать с классами через рефлексию

** DynamicClassLoader

#+begin_src clojure
  @Compiler/LOADER
#+end_src

- позволяет загружать любой байткод
  так работает deftype и т.п.
- *можно* ~(import MySuperClass)~
- *можно* import в другом классе
- и не нужна рефлексия

- разобрался с Groovy CompilationUnit
  получаю байткод в виде байтов

* Интероп с Clojure

clojure.java.api.Clojure
- var
- read

** with aka ->

#+begin_src
  (-> 1 (vector 2 3) (conj 4))
  1.with { vector.invoke(it, 2, 3) }.with { conj.invoke(it) }
  1.with(vector, 2, 3).with(conj) // расширение
#+end_src

** данные и функции отдельно

#+begin_src clojure
  {:user/name "Mikhail"
   :org/name  "GMonit"
   :ru.hsl.gmonit.apm.awesome-package/name "..."
   'foo/name  "..."
   "name"     "..."}
#+end_src

#+begin_src erb
  <%= model.:user/name %>
  <%= model.:ru.hsl.gmonit.apm.awesome-package/name %>
#+end_src

#+begin_src groovy
  def userName    = (IFn) (read ':user/name')
  def packageName = (IFn) (read ':ru.hsl.gmonit.apm.awesome-package/name')

  model.with(userName)     // расширение
  model.with(packageName)  // расширение
#+end_src

** rwith aka ->>
** tap aka doto

* Java

В Java не получится расширить Object, и придется делать явно:

#+begin_src java
  chain(obj)
      .with(vector, 2, 3)
      .rwith(map, inc)
      .tap(prn)
      .result()
#+end_src

* Другие языки вместо Groovy

- Kotlin
  Экспериментальный Scripting API не подойдет,
  нужно использовать именно компилятор
  и получать байт-код.

  API использует файлы на реальной файловой системе.
  И нельзя использовать, например [[https://github.com/google/jimfs][jimfs]] или [[https://github.com/sourcebuddy/sourcebuddy/blob/main/src/main/java/com/javax0/sourcebuddy/InMemoryJavaFileManager.java][FileManager]].
  - даже [[https://github.com/JetBrains/kotlin-compiler-server/blob/f47f6f2e713d0b32a2a28b94571f0aafa1099cc3/src/main/kotlin/com/compiler/server/compiler/components/CliUtils.kt#L108][kotlin-compiler-server]] использует временные директории
  - [[https://github.com/casid/jte/blob/main/jte-kotlin/src/main/java/gg/jte/compiler/kotlin/KotlinClassCompiler.java][jte kotlin compiler]]
  - [[https://stackoverflow.com/questions/45888068/how-do-i-run-tests-compiling-a-kotlin-file-in-memory-and-check-the-result][stack overflow]]

- Java
  Интересно рассмотреть для динамической перезагрузки генерируемого кода, например
  + JOOQ
    генерирует классы по базе данных
  + Antlr4
    герерирует парсер

  Но писать свой код ИМХО лучше на Groovy.

  примеры
  + [[https://github.com/sourcebuddy/sourcebuddy][sourcebuddy]]
  + [[https://github.com/jOOQ/jOOR/blob/main/jOOR/src/main/java/org/joor/Compile.java][JOOR]]

- [[https://github.com/janino-compiler/janino][Janino]]
  Janino is a super-small, super-fast Java™ compiler.

  Простое API. Легко получить байты для DynamicClassLoader.
  Не все фичи Java поддерживаются.

* Demo

- тесты
  - исключения
- бенчмарки
  - протоколы
- реализация

* Дальнейшие шаги

- название
- компиляция
  компилируем неймспейс, компилируются и груви классы
- примеры
- ideas.org
